### ISSUE TITLE
[Bug] Melee Deadzone

### ISSUE THREAD

**Issue by VeraNala** [FFXIV-CombatReborn/LTSDefaults#109]
RSR will attempt to use Melee weaponskills on targets that are out of range (just slightly beyond max melee) rather than Ranged ones, 
As well as in some cases where it is just within max melee, perform no actions whatsoever, leading to a deadzone where no abilities are being used.
Most evident on Sohm Al drakespores, or any other stationary enemy, and easily reproducible on a training dummy.

Similar Issue on RDM -> Where even while within melee range (max melee-ish) it will opt to NOT use melee combo even though it is available unless you inch forward an arbitrary amount of distance.

**Comment by LTS-FFXIV** [comment]
This is by design so RSR doesn't immediately use a ranged skill when you hit max melee, there is no way to program in if user intention is to stay out or if they will be back in melee range soon as RSR cant read players mind (yet).

**Comment by VeraNala** [comment]
Sorry, I'll expand on this a bit cause maybe I'm not fully understanding.
Far outside of max melee - > character will use ranged skills as expected.
Just outside of max melee - > RSR will attempt to use melee skills although target is out of range.
At max melee - > character will use NO skills, even though the target IS within range.
Melee - > Normal behavior.

Is this still by design?
