### ISSUE TITLE
SAM applying DoT on same target

### ISSUE THREAD

**Issue by ebsword** [FFXIV-CombatReborn/LTSDefaults#12]
During an Expert roulette in trash packs the SAM rotation uses Higanbana (the dot) on a mob with a large health pool. Irrespective of whether that is a dps gain when they sometimes melt, when there's two enemies with large health pools RSR does not switch targets and instead keeps reapplying Higanbana on the same mob.

**Comment by Tykku** [comment]
This is part of the targeting issue that's currently being worked on, stand by.

**Comment by Tykku** [comment]
Assuming fixed in the targeting fix for RSR, if it continues please reopen.
