### ISSUE TITLE
[Testing Rotation] MCH

### ISSUE THREAD

**Issue by Alkeyd** [FFXIV-CombatReborn/LTSDefaults#30]
In opener MCH don't use Reassemble for Air Anchor and use Reassemble but skip Chain Saw as First hit for Wild Fire starting with Heat Blast and wasting 1 Reassemble in it

**Comment by Tykku** [comment]
~~Why must you break things?~~ Yea you're right :( working on it now lol

**Comment by Alkeyd** [comment]
S2

**Comment by Tykku** [comment]
Fixed in #31  Thank you
