### ISSUE TITLE
DNC: Delayed Tech Step when using condition.

### ISSUE THREAD

**Issue by Lockehart** [FFXIV-CombatReborn/LTSDefaults#39]
When 'Target is NOT a boss (icon)' condition is enabled, Tech Step will be delayed beyond flourish > fan dance iii > fan dance iv (and also occasionally use a feather on fan dance i) before tech step begins at the start of a fight.

Ex.: Standard Step > Pattern > Standard Finish > Flourish > FD III > FD IV > Tech Step

Without that condition it goes as normal.

Standard Step > Pattern > Standard Finish > Flourish > Tech Step > Pattern > Tech Finish > Fan Dances

**Comment by Tykku** [comment]
Issue was with missing conditions, stated fixed in discord, closing issue.
