### ISSUE TITLE
Earthly Star no longer being auto casted as of version v4.0.2.3

### ISSUE THREAD

**Issue by ShiftyKiwi** [FFXIV-CombatReborn/LTSDefaults#40]
As of version 4.0.2.3 earthly star on LTS rotations is no longer being auto casted when auto rotation is enabled.

This was found  to be the case in an alliance raid setting. Upon further testing in other environments such as solo duties and open world content, the result was the same. Other methods were tested to try and solve the issue, such as forced conditions and disabling and re-enabling the plugin, without any success.

**Comment by Tykku** [comment]
Fixed in RSR update 4.1.0.6
