### ISSUE TITLE
[BRD] is not pooling Bloodletter/Rain of Death

### ISSUE THREAD

**Issue by Komakuo** [FFXIV-CombatReborn/LTSDefaults#43]
Bard is currently just dumping Bloodletter/Rain of Death charges, usually leading to 1-2/3 stacks missing during burst-windows.

Quoting XIVanalysis: 
At least three uses of **Bloodletter** or **Rain of Death** should occur during every **Raging Strikes** window. Make sure you pool your **Bloodletter** or **Rain of Death** charges during **Army's Paeon**.

![5464564564564](https://github.com/FFXIV-CombatReborn/LTSDefaults/assets/165340173/2e23cc35-9eaa-4834-93e9-71c562cd9bf0)

**Comment by Tykku** [comment]
Try the Beta Bard

**Comment by Tykku** [comment]
Fixed in #46 for Beta Bard

**Comment by Tykku** [comment]
fixed in #51
