### ISSUE TITLE
Double Doh-Ton

### ISSUE THREAD

**Issue by Rabalaba** [FFXIV-CombatReborn/LTSDefaults#52]
Ninja uses doton twice, probably because the server doesn't give the player the doton buff right away.  Suggested fix add !RecordActions[0..10].Any(x => x.Action.RowId == DotonPvE.ID) && !RecordActions[0..10].Any(x => x.Action.RowId == DotonPvE_18880)  or something else similar

**Comment by Rabalaba** [comment]
can confirm this fixed for me 
if (!RecordActions[0..10].Any(x => x.Action.RowId == DotonPvE.ID) && !RecordActions[0..10].Any(x => x.Action.RowId == DotonPvE_18880.ID) && !Player.HasStatus(true, StatusID.Doton))
     if (mudraState.CastDoton(out actionID))
 {
     IBaseAction Thisaction = new BaseAction((ActionID)actionID);
     if (actionID != 0)
     {
         if (Thisaction.CanUse(out act, skipAoeCheck: true, skipCastingCheck: true, skipClippingCheck: true, skipComboCheck: true, skipStatusProvideCheck: true, usedUp: true)) return true;
     }
 }

**Comment by Rabalaba** [comment]
this is safer
if (RecordActions != null)
{
    // Limit to the most recent 10 elements (or less if RecordActions has fewer elements)
    var recentActions = RecordActions.Take(10);

    if (!recentActions.Any(x => x.Action.RowId == DotonPvE.ID || x.Action.RowId == DotonPvE_18880.ID) && !Player.HasStatus(true, StatusID.Doton))
    {
        if (mudraState.CastDoton(out actionID))
        {
            IBaseAction Thisaction = new BaseAction((ActionID)actionID);
            if (actionID != 0)
            {
                if (Thisaction.CanUse(out act, skipAoeCheck: true, skipCastingCheck: true, skipClippingCheck: true, skipComboCheck: true, skipStatusProvideCheck: true, usedUp: true)) return true;
            }
        }
    }
}

**Comment by Tykku** [comment]
Will rewrite nin in Dawn Trail
