### ISSUE TITLE
During the period of Meikyo,it continues to use single-target attacks (Gekko, Kasha, Yukikaze) instead of Mangetsu and Oka when facing multiple targets.

### ISSUE THREAD

**Issue by FlameShadow777** [FFXIV-CombatReborn/LTSDefaults#63]
Regular AoE attacks work fine as usual. However, the specific AoE in question here refers to the Samurai's use of single-target attacks (Gekko, Kasha, Yukikaze) during the Meikyo period instead of using Mangetsu and Oka against multiple targets.

**Comment by Tykku** [comment]
Fixed in one of em I don't remember
