### ISSUE TITLE
NIN Ninjutsu Issues

### ISSUE THREAD

**Issue by Lockehart** [FFXIV-CombatReborn/LTSDefaults#9]
Issue 1.: Doton is being used while in motion between packs, leaving the sand pit behind doing no damage, wasting a ninjutsu.  When doton is given a 'force disable while moving' condition, it will either still place or will do the mundra pattern but not cast Doton, just leaving the countdown to expire.  When Doton (and I assume every ninjutsu is affected by this as well) is completely disabled via RSR, the mundra pattern will still fire off, but will not cast Doton, leaving the timer to expire.

Idea of a fix is tying mundras to the abilities themselves instead of the rotation (I know nothing of how this works or if this is how it already works, but just guessing).  Quick patch would be to prioritize Katon and only start Doton's pattern if still for an extended period of time.

Coding this will probably be an absolute nightmare and not really necessary since the rotation works well enough as a general purpose rotation and it's not meant to parse 99.  So if this doesn't get tackled, I would not blame you in the slightest.  You guys go above and beyond as is.

Issue 2.: Rotation continues to prioritize Suiton over Raiton even when not needed, sometimes casting twice in a row.

**Comment by Tykku** [comment]
Ninja is on my list but not a priority. Keep this open for now please.

**Comment by Tykku** [comment]
Mudras fixed in RSR update, double suiton fixed in Nin Beta, Will move to live soon
